# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kZ5k6Qd1_HTjIyXGbRZPH9Up-7zfwoSd
"""

from transformers import pipeline
import pandas as pd

# Initialize emotion classifier (zero-shot for general-purpose, or emotion-specific models)
emotion_classifier = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base", return_all_scores=True)

# Sample social media posts
texts = [
    "I just got a promotion at work! Feeling amazing 🎉",
    "This is the worst day of my life.",
    "Meh, today was okay. Nothing special.",
    "Why does this always happen to me? So frustrating.",
    "I can't stop smiling after our date last night. ❤️"
]

# Analyze emotions
results = []
for text in texts:
    prediction = emotion_classifier(text)[0]  # List of dicts with 'label' and 'score'
    sorted_prediction = sorted(prediction, key=lambda x: x['score'], reverse=True)
    top_emotion = sorted_prediction[0]
    results.append({
        "Text": text,
        "Top Emotion": top_emotion['label'],
        "Score": round(top_emotion['score'], 3)
    })

# Display results
df = pd.DataFrame(results)
print(df)